[package]
name = "snapmail"
version = "0.0.1"
authors = ["doute.d@gmail.com"]
edition = "2018"

# Ensure that this is not inside of any other workspace.
# This crate should be an implementation detail of test_utils_wasm and
# therefore shouldn't be mentioned in the top-level Cargo.toml
[workspace]

[lib]
name = "snapmail"
crate-type = [ "cdylib", "rlib" ]

[dependencies]
holochain_serialized_bytes = "=0.0.40"
holochain_wasmer_guest = "=0.0.36"
holochain_zome_types = { version = "=0.0.1", path = "../../../holochain-rsm/crates/zome_types" }
hdk3 = { path = "../../../holochain-rsm/crates/hdk" }
holo_hash_core = { path = "../../../holochain-rsm/crates/holo_hash_core" }

serde = "=1.0.104"
test_wasm_common = { version = "=0.0.1", path = "../../../holochain-rsm/crates/test_utils/wasm_common" }
