[package]
name = "snapmail"
version = "0.0.1"
authors = ["doute.d@gmail.com"]
edition = "2018"

# Ensure that this is not inside of any other workspace.
# This crate should be an implementation detail of test_utils_wasm and
# therefore shouldn't be mentioned in the top-level Cargo.toml
[workspace]

[lib]
name = "snapmail"
crate-type = [ "cdylib", "rlib" ]

[dependencies]
shrinkwraprs = "0.3.0"
chrono = "=0.4.6"
serde = "=1.0.104"
strum = "0.19"
strum_macros = "0.19"
derive_more = "0.99.9"

#hdk3 = { git = "ssh://git@github.com/holochain/holochain.git", rev = "4714fbddc48f1f9987c9f574b8d06510ea58ab16", package = "hdk3" }
hdk3 = { path = "../../../holochain-rsm/crates/hdk3" }
holo_hash = { path = "../../../holochain-rsm/crates/holo_hash" }
#test_wasm_common = { version = "=0.0.1", path = "../../../holochain-rsm/crates/test_utils/wasm_common" }

#dna_help = { path = "../../../../crates/dna_help" }


